title: Winding Tree - Developer Portal
email: hello@windingtree.com
description: >- 
  Get started with software development on the Winding Tree decentralized marketplace. 
  Run your own OTA or expose your content.
baseurl: "/"
url: ""
twitter_username: windingtree
github_username:  windingtree
telegram_username:  windingtree

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-plantuml

# Just-the-docs Plugin settings
logo: "/assets/images/winding-tree-logo.png"
aux_links:
  "Winding Tree website":
    - "//windingtree.com"
  "Winding Tree on GitHub":
    - "//github.com/windingtree"
aux_links_new_tab: false
footer_content: "<a href=\"https://windingtree.com\">Winding Tree</a> developer portal."
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/windingtree/developer-portal"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"
color_scheme: wt

# PlantUML Plugin settings
plantuml:
  url:	 'http://www.plantuml.com/plantuml/png/{code}'
  assets:  '_assets/images/plantuml/'

# Define assets
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
