title: Winding Tree - Developer Portal
email: hello@windingtree.com
description: >- 
  Get started with software development on the Winding Tree decentralized marketplace. 
  Run your own OTA or expose your content.
baseurl: ""
url: ""
twitter_username: windingtree
github_username:  windingtree
telegram_username:  windingtree

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Define collection for the documentation page
collections:
  doc:
    output: true
    permalink: /_doc/:slug/

# Define assets
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
